// One-time WebP generator: scans public/ and src/ for raster images
// and produces .webp siblings (skips if .webp already exists or is newer than source).
//
// NOTE: WebP variants are generated by the `prebuild` npm script.
// Components are NOT yet updated to use <picture> with <source type="image/webp">;
// adoption can be rolled out later by wrapping <img> tags in <picture> elements.
import { promises as fs } from "node:fs";
import path from "node:path";
import sharp from "sharp";

const ROOTS = ["public", "src"];
const EXTS = [".jpg", ".jpeg", ".png"];
const QUALITY = 85;

async function walk(dir) {
  const out = [];
  let entries;
  try { entries = await fs.readdir(dir, { withFileTypes: true }); } catch { return out; }
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) {
      if (e.name === "node_modules" || e.name === "dist" || e.name === ".git") continue;
      out.push(...(await walk(full)));
    } else if (EXTS.includes(path.extname(e.name).toLowerCase())) {
      out.push(full);
    }
  }
  return out;
}

async function convert(file) {
  const webp = file.replace(/\.(jpe?g|png)$/i, ".webp");
  try {
    const [srcStat, webpStat] = await Promise.all([fs.stat(file), fs.stat(webp).catch(() => null)]);
    if (webpStat && webpStat.mtimeMs >= srcStat.mtimeMs) return false; // already up-to-date
  } catch {}
  await sharp(file).webp({ quality: QUALITY }).toFile(webp);
  return true;
}

(async () => {
  let total = 0, written = 0;
  for (const root of ROOTS) {
    const files = await walk(root);
    total += files.length;
    for (const f of files) {
      try {
        if (await convert(f)) { written++; process.stdout.write("."); }
      } catch (err) {
        console.warn("\nFailed:", f, err.message);
      }
    }
  }
  console.log(`\nWebP generation: ${written} written / ${total} candidates`);
})();
